describe('Validação Cupons de Desconto', () => {
  it('Validação cupom FRETEGRATIS', () => {
    cy.visit('/destaque-produto-em-destaque')
    cy.contains('a', 'Comprar').click()
    cy.get('#calcularFrete').type('88010000')
    cy.get('#btn-frete').click()
    cy.get('input[name="formaEnvio"]').should('be.visible', {timeout: 10000})
    cy.get('input[name="formaEnvio"]').last().click()
    cy.intercept('GET', '/carrinho/valor-descontos').as('esperaTotal')
    cy.wait('@esperaTotal')
    cy.get('.total > .titulo').invoke('text').then(($totalComFrete) => {
      expect($totalComFrete).to.include('R$ 145,10')
    })
    cy.get('#usarCupom').type('FRETEGRATIS')
    cy.get('#btn-cupom').click()
    cy.get('.total > .titulo').should('be.visible', {timeout: 10000})
    cy.get('.total > .titulo').invoke('text').then(($totalSemFrete) => {
      expect($totalSemFrete).to.include('R$ 110,00')
    })
  })

  it('Validação cupom 10OFF', () => {
    cy.visit('/destaque-produto-em-destaque')
    cy.contains('a', 'Comprar').click()
    cy.get('#calcularFrete').type('88010000')
    cy.get('#btn-frete').click()
    cy.intercept('GET', '/carrinho/valor-descontos').as('esperaTotal')
    cy.wait('@esperaTotal')
    cy.get('input[name="formaEnvio"]').last().click()
    cy.intercept('GET', '/carrinho/valor-descontos').as('esperaTotal')
    cy.wait('@esperaTotal')
    cy.get('.total > .titulo').should('have.text', 'R$ 145,10')
    cy.get('#usarCupom').type('10OFF')
    cy.get('#btn-cupom').click()
    cy.get('.cupom-codigo').should('have.text', '10OFF')
    cy.contains('.cupom-valor', '(frete não incluso)').should('be.visible')
    cy.get('.total > .titulo').should('have.text', 'R$ 134,10')
  })

  it('Validação cupom 30REAIS', () => {
    cy.visit('/destaque-produto-em-destaque')
    cy.contains('a', 'Comprar').click()
    cy.get('#calcularFrete').type('88010000')
    cy.get('#btn-frete').click()
    cy.intercept('GET', '/carrinho/valor-descontos').as('esperaTotal')
    cy.wait('@esperaTotal')
    cy.get('input[name="formaEnvio"]').last().click()
    cy.intercept('GET', '/carrinho/valor-descontos').as('esperaTotal')
    cy.wait('@esperaTotal')
    cy.get('.total > .titulo').should('have.text', 'R$ 145,10')
    cy.get('#usarCupom').type('30REAIS')
    cy.get('#btn-cupom').click()
    cy.contains('.cupom-valor', '(frete não incluso)').should('be.visible')
    cy.contains('.cupom-codigo', '30REAIS').should('be.visible')
    cy.get('.total > .titulo').should('have.text', 'R$ 115,10')
  })

  it('Validação cupom AJJFLWBHH', () => {
    cy.visit('/destaque-produto-em-destaque')
    cy.contains('a', 'Comprar').click()
    cy.get('#calcularFrete').type('88010000')
    cy.get('#btn-frete').click()
    cy.intercept('GET', '/carrinho/valor-descontos').as('esperaTotal')
    cy.wait('@esperaTotal')
    cy.get('input[name="formaEnvio"]').last().click()
    cy.intercept('GET', '/carrinho/valor-descontos').as('esperaTotal')
    cy.wait('@esperaTotal')
    cy.get('.total > .titulo').should('have.text', 'R$ 145,10')
    cy.get('#usarCupom').type('AJJFLWBHH')
    cy.get('#btn-cupom').click()
    cy.get('#cupom_desconto').invoke('text').then(($valor) =>{
      expect($valor).to.includes('5 %')
    })
    cy.contains('.cupom-codigo', 'AJJFLWBHH').should('be.visible')
    cy.get('.total > .titulo').should('have.text', 'R$ 137,85')
  })

  it('Validação cupom CUPOMVENCIDO', () => {
    cy.visit('/destaque-produto-em-destaque')
    cy.contains('a', 'Comprar').click()
    cy.get('#calcularFrete').type('88010000')
    cy.get('#btn-frete').click()
    cy.intercept('GET', '/carrinho/valor-descontos').as('esperaTotal')
    cy.wait('@esperaTotal')
    cy.get('input[name="formaEnvio"]').last().click()
    cy.intercept('GET', '/carrinho/valor-descontos').as('esperaTotal')
    cy.wait('@esperaTotal')
    cy.get('.total > .titulo').should('have.text', 'R$ 145,10')
    cy.get('#usarCupom').type('CUPOMVENCIDO')
    cy.get('#btn-cupom').click()
    cy.contains('O cupom não é válido.').should('be.visible')
    cy.get('.total > .titulo').should('have.text', 'R$ 145,10')
  })

  it('Validação cupom 20LIMITADO', () => {
    cy.visit('/destaque-produto-em-destaque')
    cy.contains('a', 'Comprar').click()
    cy.get('#calcularFrete').type('88010000')
    cy.get('#btn-frete').click()
    cy.intercept('GET', '/carrinho/valor-descontos').as('esperaTotal')
    cy.wait('@esperaTotal')
    cy.get('input[name="formaEnvio"]').last().click()
    cy.intercept('GET', '/carrinho/valor-descontos').as('esperaTotal')
    cy.wait('@esperaTotal')
    cy.get('.total > .titulo').should('have.text', 'R$ 145,10')
    cy.get('#usarCupom').type('20LIMITADO')
    cy.get('#btn-cupom').click()
    cy.contains('Cupom não encontrado.').should('not.be.visible')
    cy.contains('.cupom-codigo', '20LIMITADO').should('be.visible')
    cy.get('.total > .titulo').should('not.have.text', 'R$ 145,10')
  })

})

